### ISSUE TITLE
Added another path option to reach autoload.php

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-development-mode#1]
Same issue as described [here](https://github.com/zendframework/zend-expressive-tooling/pull/28#issuecomment-300173700).

There is no symlink in macOS, just a copy of executable which cannot locate autoloader. But if we, for example, create project inside Docker container using Alpine 3.10 as base image, it creates symlink to `vendor/zfcampus/zf-development-mode/bin/zf-development-mode` and everything works fine as expected.

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.

---

Originally posted by @gailimov at https://github.com/zfcampus/zf-development-mode/pull/37

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-development-mode/pull/7 for it.
