### ISSUE TITLE
composer development-status not able to find /vendor/autoload.php file

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-development-mode#2]
- [x] I was not able to find an [open](https://github.com/zfcampus/zf-development-mode/issues?q=is%3Aopen) or [closed](https://github.com/zfcampus/zf-development-mode/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

After a fresh install of Zend Expressive using `$ composer create-project zendframework/zend-expressive-skeleton expressive` from within the root directory of the application, try to execute any of the `development-*` scripts using Composer.

### Command to duplicate issue

```bash
$ cd /path/to/expressive/root
$ composer development-status
```

### Expected results

I would expect to receive "Development mode is ENABLED"

### Actual results

Instead, the script is not able to find the autoload.php. This is because the script has 2 possible locations to search for `/vendor/autoload.php` by using `__DIR__` + added locations. However, when calling `composer` from the application root the result of `__DIR__` is `/vendor/bin`. Therefore the following locations will not find `/vendor/autoload.php`.

```php
__DIR__ . '/../../../autoload.php';
__DIR__ . '/../vendor/autoload.php';
```

What is needed is `__DIR__ . '/../autoload.php'`.

NOTE: My experience was on Ubuntu 18.04 using `/usr/bin/composer` to use php via cli.

---

Originally posted by @adamculp at https://github.com/zfcampus/zf-development-mode/issues/36

**Comment by samsonasik** [comment]
fixed by https://github.com/laminas/laminas-development-mode/pull/7
