### ISSUE TITLE
Is there a way to check for development mode in code, php code

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-development-mode#4]
How to check if the development mode is enabled or not in code

---

Originally posted by @waqarprojectinertia at https://github.com/zfcampus/zf-development-mode/issues/28

**Comment by weierophinney** [comment]
@waqarprojectinertia Enabling development mode copy files:
- `config/development.config.php.dist` to `config/development.config.php`
- `config/autoload/development.local.php.dist` to `config/autoload/development.local.php`

so if you want to check it in code, please check if you have these files. It means you have enabled development mode.

You can also check status of development mode using console command:
```console
$ ./vendor/bin/zf-development-mode status
```

---

Originally posted by @michalbundyra at https://github.com/zfcampus/zf-development-mode/issues/28#issuecomment-282975859

**Comment by samsonasik** [comment]
Via code, you can check with : 
```php
var_dump((file_exists(\Laminas\DevelopmentMode\Status::DEVEL_CONFIG)));
```
